markdown: kramdown
kramdown:
  math_engine: mathjax

highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
environment: prod
url: "http://gregorygundersen.com"

plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-katex

scholar:
  style: apa
  locale: en
  source: ./_bibliography
  bibliography: references.bib
  sort_by: year,month
  order: descending