markdown: kramdown
kramdown:
  math_engine: mathjax

highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
environment: prod
url: "http://gregorygundersen.com"

# Plugins
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag