name: Build and Deploy Jekyll Site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: false  # Changed to false to handle platform-specific setup

    - name: Setup Bundler
      run: |
        rm -f Gemfile.lock
        bundle lock --add-platform x86_64-linux
        bundle lock --add-platform ruby
        bundle install

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle add jekyll -v "4.2.0"
        bundle add jekyll-scholar
        bundle add webrick
        bundle install

    - name: Build Site
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site